```{r}
x<-10
y<-9
c<-x-y
my_numeric <-423.8
my_character ="universe"
my_logical= FALSE

```


vectores
```{r}
numeric_vector <- c(1,2,3)
character_vector <- c("a","b","c")
    boolean_vector <- c(TRUE,FALSE,TRUE)
    
    
    poker_vector <-c(140,-50,-20,-120,240)
    roulettevector <-c(-24,-50,10,350,10)
    ```

nombrando vectores
```{r}
names(poker_vector) <-c("Monday","Tuesday","Wednesday","Thursday","Friday")

  poker_vector
    ```

selection by comparison
```{r}
age <- 21
age >=18

selection_vector <- poker_vector>0
selection_vector

poker_winning_days <- poker_vector[selection_vector]
poker_winning_days
```
vector selection
```{r}
poker_vector
poker_vector[3]
poker_vector[c(2,3,4)]

poker_vector[2:5]
```

matrices
```{r}
matrix(1:9,byrow=TRUE,nrow = 3)
```

```{r}
new_hope <-c(460,998,314,4)
empire_strikes<-c(290,475,247,9)
return_jedi<-c(309,306,165,8)

box_office<-c(new_hope, empire_strikes, return_jedi)

stars_wars_matrix<-matrix(box_office, byrow=TRUE,nrow=3)

```
Factor
```{r}
sex_vector <-c("Male","Female","Male","Male")

factor_sex_vector<-factor(sex_vector)
factor_sex_vector

```
```{r}
temperatura_vector <- c("High","Low","High","Low","Medium")
factor_temperature_vector <-factor(temperatura_vector,order=TRUE, levels=c("Low","Medium","High"))
factor_temperature_vector
```

factor levels
```{r}
survey_vector <-c("M","F","F","M","M")
factor_survey_vector <-factor(survey_vector)
factor_survey_vector
levels(factor_survey_vector) <-c("Female","Male")

```

ordered factors
```{r}
male<-factor_survey_vector[1]
female<-factor_survey_vector[2]
male >female

speed_vector <-c("medium","slow","slow","medium","fast")

factor_speed_vector <-factor(speed_vector,ordered = TRUE, levels=c("slow","medium","fast"))

speed_1 <-factor_speed_vector[2]
speed_5 <-factor_speed_vector[5]
speed_5>speed_1

```

